openapi: 3.0.0
info:
  title: n8n API
  description: A test API definition for experimenting with Redocly
  version: 1.0.0
servers:
  - url: https://api.n8n.com
paths:
  /health:
    get:
      summary: Health check
      responses:
        '200':
          description: OK
  /users:
    get:
      summary: List all users
      responses:
        '200':
          description: A list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
